export const LettersMock = [
  {
    title: "Как дела? Я проверяю максимальную длину заголовка, чтобы она не вылезала за границы поля",
    isImportant: false,
    sender: "Denis",
    senderMail: "denis@hotmail.com",
    date: 1681317032706,
    isRead: true,
  },
  {
    title: "Почему ты не пишешь?",
    isImportant: true,
    sender: "Mira",
    senderMail: "mira@gmail.com",
    date: 1661358932706,
    isRead: true,
  },
  {
    title: "Фотки со вчерашнего дня",
    isImportant: true,
    sender: "Чувак с супер длинным именем",
    senderMail: "genius@gmail.com",
    date: 1655511232706,
    isRead: false,
  },
  {
    title: "Скидка на избранный товар",
    isImportant: false,
    sender: "OZON",
    senderMail: "noreply@ozon.ru",
    date: 1451315532706,
    isRead: true,
  },
  {
    title: "Вы интересовались товаром \"Крем от облысения\"",
    isImportant: false,
    sender: "OZON",
    senderMail: "noreply@ozon.ru",
    date: 1681117032000,
    isRead: true,
  },
  {
    title: "Приходи на пикник",
    isImportant: false,
    sender: "Denis",
    senderMail: "denis@hotmail.com",
    date: 1681017032706,
    isRead: false,
  },
];
